name: bond
description: Bond project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  one_studio_core:
    git:
      url: https://github.com/onestudio-co/one-studio-core.git
      ref: main
  easy_localization: ^3.0.1
  dartz: ^0.10.1
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  auto_route: ^4.2.1
  flutter_svg: ^1.0.3
  intl: ^0.17.0

  # utils
  flutter_native_splash: ^2.2.8

  # Firebase
  firebase_analytics: ^9.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.2.1
  flutter_lints: ^1.0.0
  http_mock_adapter:
    git:
      url: https://github.com/lomsa-dev/http-mock-adapter.git
      ref: main
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  bloc_test: ^9.0.2
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/langs/
