name: fixit
description: Fixit project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.2.3
  shared_preferences: ^2.0.13
  dio: ^4.0.4
  device_info: ^2.0.3
  dartz: ^0.10.1
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  sms_autofill: ^2.2.0
  auto_route: ^3.2.2
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  package_info_plus: ^1.3.0
  flutter_config: ^2.0.0
  cupertino_icons: ^1.0.2
  bloc_test: ^9.0.2
  mockito: ^5.0.17
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  auto_route_generator: ^3.2.1

flutter:

  uses-material-design: true

  assets:
    # - config/app_config.json
    - assets/images/
    - assets/fixture_reader/
    - assets/fixture_reader/settings/
    - assets/fixture_reader/conversations/
    - assets/fixture_reader/conversationsMessage/
    - assets/fixture_reader/sendMessage/
    - assets/sounds/
  fonts:
    - family: Famtree-Bold
      fonts:
        - asset: assets/fonts/Famtree-Bold.ttf

    - family: Famtree-Light
      fonts:
        - asset: assets/fonts/Famtree-Light.ttf

    - family: Famtree-Medium
      fonts:
        - asset: assets/fonts/Famtree-Medium.ttf

    - family: Famtree-Regular
      fonts:
        - asset: assets/fonts/Famtree-Regular.ttf
