name: one_studio_core
description: Flutter package which contain the core file of one studio apps.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  device_info: ^2.0.3
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.13
  package_info_plus: ^1.3.0
  faker: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

